variables:
  CLI_VERSION: 7.3.7

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - test
  - build

before_script:
  - npm install --silent

test:
  image: trion/ng-cli-karma:${CLI_VERSION}
  stage: test
  tags:
    - docker
  script: node_modules/.bin/ng test --watch=false

build:
  image: trion/ng-cli:${CLI_VERSION}
  stage: build
  tags:
    - docker
  script: node_modules/.bin/ng build --prod
